---
kind: pipeline
type: docker
name: build & deploy

concurrency:
  limit: 2

steps:
  # - name: build & deploy
  #   image: plugins/docker
  #   commands:
  #     - ./scripts/build.sh
  #     - docker push eldekyfin/omv

  - name: docker build & Publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo: eldekyfin/omv
      tags: latest,0.1,0.1.0
