---
kind: pipeline
type: docker
name: build & deploy

concurrency:
  limit: 2

steps:
  - name: build & deploy
    image: debian:bullseye
    commands:
      - ./scripts/build.sh
      - docker push eldekyfin/omv
